hospital/urls.py
from django.urls import path
from . import views

urlpatterns=[
				path('', views.login_form),
				path('submit_form/', views.submit_form),
				path('go/',views.go, name='go'),
				path('invoice/',views.invoice),
				path('main/',views.main, name='main'),
				path('log/',views.log, name='log'),

				path('ins',views.ins, name='ins'),
				path('show',views.show, name='show'),
				path('edit/<int:inst_id>',views.edit), 
				path('update/<int:inst_id>',views.update),
				path('delete/<int:inst_id>',views.delete),

				path('dep',views.dep),
				path('show1',views.show1),
				path('edit1/<int:dept_id>',views.edit1), 
				path('update1/<int:dept_id>',views.update1),
				path('delete1/<int:dept_id>',views.delete1),

				path('con',views.con),
				path('show2',views.show2),
				path('delete2/<int:con_id>',views.delete2),

				path('ord',views.ord),
				path('show3',views.show3),
				path('delete3/<int:ord_id>',views.delete3),

				path('sto',views.sto),
				path('show4',views.show4),
				path('delete4/<int:st_id>',views.delete4),
]

hospital/models.py
from django.db import models
from decimal import Decimal
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
class instruments(models.Model):
	inst_id= models.AutoField(primary_key=True)
	def individual():
		return 'some string'
	inst_name= models.CharField(max_length=30,default=individual)
	cost= models.DecimalField(max_digits=10,decimal_places=2,default=Decimal('00000000.00'),validators=[MinValueValidator(Decimal('0.01'))])
	class Meta:
		db_table= "instruments"

class departments(models.Model):
	dept_id= models.AutoField(primary_key=True)
	def individual():
		return 'some string'
	dept_name= models.CharField(max_length=30,default=individual)
	class Meta:
		db_table= "departments"

class contracts(models.Model):
	con_id= models.AutoField(primary_key=True)
	def individual():
		return 'some string'
	con_com= models.CharField(max_length=30,default=individual)
	con_amt= models.DecimalField(max_digits=10,decimal_places=2,default=Decimal('00000000.00'),validators=[MinValueValidator(Decimal('0.01'))])
	con_equip= models.CharField(max_length=30,default=individual)
	class Meta:
		db_table= "contracts"

class order(models.Model):
	ord_id= models.AutoField(primary_key=True)
	Inst_id= models.ForeignKey(instruments,on_delete=models.CASCADE)
	Con_id= models.ForeignKey(contracts, on_delete=models.CASCADE)
	Dept_id= models.ForeignKey(departments, on_delete=models.CASCADE)
	ord_quan= models.IntegerField(default=0,validators=[MinValueValidator(1)])
	class Meta:
		db_table= "orders"

class stock(models.Model):
	st_id= models.AutoField(primary_key=True)
	order_id= models.ForeignKey(order, on_delete=models.CASCADE)
	depa_id= models.ForeignKey(departments, on_delete=models.CASCADE)
	quantity= models.IntegerField(default=0,validators=[MinValueValidator(1)])
	class Meta:
		db_table= "stocks"

hospital/forms.py
from django import forms 
from hospital.models import instruments
from hospital.models import departments
from hospital.models import contracts
from hospital.models import order
from hospital.models import stock

class instrumentsform(forms.ModelForm):
	class Meta:
		model= instruments
		fields= "__all__"

class departmentsform(forms.ModelForm):
	class Meta:
		model=departments
		fields="__all__"

class contractsform(forms.ModelForm):
	class Meta:
		model=contracts
		fields="__all__"

class orderform(forms.ModelForm):
	class Meta:
		model=order
		fields="__all__"

class stockform(forms.ModelForm):
	class Meta:
		model=stock
		fields="__all__"

hospital/views.py
from django.shortcuts import render,redirect
from hospital.forms import instrumentsform
from hospital.forms import departmentsform
from hospital.forms import contractsform
from hospital.forms import orderform
from hospital.forms import stockform
from hospital.models import instruments
from hospital.models import departments
from hospital.models import contracts
from hospital.models import order
from hospital.models import stock
from django.http import HttpResponse


# Create your views here.
def ins(request):
	if request.method == "POST":
		form = instrumentsform(request.POST)
		if form.is_valid():
			try:
				form.save()
				return redirect("/show")
			except:
				pass
	else:
		form= instrumentsform()
	return render(request,"instruments.html", {'form':form})

def show(request):
	instrumenti= instruments.objects.all()
	return render(request,"show.html",{'instrumenti':instrumenti})

def edit(request, inst_id):
	insti= instruments.objects.get(inst_id=inst_id)
	return render(request,"edit.html",{'insti':insti})

def update(request, inst_id):
	insti= instruments.objects.get(inst_id=inst_id)
	form= instrumentsform(request.POST, instance= insti)
	if form.is_valid():
		form.save()
		return redirect('/show')
	return render(request,"edit.html",{'insti':insti})
	
def delete(request, inst_id):
	insti= instruments.objects.get(inst_id=inst_id)
	insti.delete()
	return redirect("/show")


def dep(request):
	if request.method == "POST":
		form = departmentsform(request.POST)
		if form.is_valid():
			try:
				form.save()
				return redirect("/show1")
			except:
				pass
	else:
		form= departmentsform()
	return render(request,"departments.html", {'form':form})

def show1(request):
	departmenti= departments.objects.all()
	return render(request,"show1.html",{'departmenti':departmenti})

def edit1(request,dept_id):
	depti= departments.objects.get(dept_id=dept_id)
	return render(request,"edit1.html",{'depti':depti})
def update1(request,dept_id):
	depti= departments.objects.get(dept_id=dept_id)
	form= departmentsform(request.POST, instance= depti)
	if form.is_valid():
		form.save()
		return redirect('/show1')
	return render(request,"edit1.html",{'depti':depti})
def delete1(request, dept_id):
	depti= departments.objects.get(dept_id=dept_id)
	depti.delete()
	return redirect("/show1")


def login_form(request):
	return render(request, 'login_register.html')

def submit_form(request):
	username= request.GET['username']
	password= request.GET['password']
	if username == "Akmsinv" and password == "Akms@2020":
		return render(request, 'main.html')
	else:
		return HttpResponse('Invalid username or password')

def go(request):
	return render(request, 'inventory_main.html')

def invoice(request):
	return render(request,'invoice.html')

def main(request):
	return render(request, 'main.html')

def log(request):
	return render(request, 'login_register.html')

def con(request):
	if request.method == "POST":
		form = contractsform(request.POST)
		if form.is_valid():  
			try:
				form.save()
				return redirect("/show2")
			except:
				pass
	else:
		form= contractsform()
	return render(request,"contracts.html", {'form':form})

def show2(request):
	contracti= contracts.objects.all()
	return render(request,"show2.html",{'contracti':contracti})

def edit2(request,con_id):
	coni= contracts.objects.get(con_id=con_id)
	return render(request,"edit2.html",{'coni':coni})

def delete2(request,con_id):
	coni= contracts.objects.get(con_id=con_id)
	coni.delete()
	return redirect("/show2")


def ord(request):
	if request.method == "POST":
		form = orderform(request.POST)
		if form.is_valid():  
			try:
				form.save()
				return redirect("/show3")
			except:
				pass
	else:
		form= orderform()
	return render(request,"orders.html", {'form':form})

def show3(request):
	orderi= order.objects.all()
	return render(request,"show3.html",{'orderi':orderi})

def delete3(request,ord_id):
	ordi= order.objects.get(ord_id=ord_id)
	ordi.delete()
	return redirect("/show3")


def sto(request):
	if request.method == "POST":
		form = stockform(request.POST)
		if form.is_valid():  
			try:
				form.save()
				return redirect("/show4")
			except:
				pass
	else:
		form= stockform()
	return render(request,"stocks.html", {'form':form})

def show4(request):
	stocki= stock.objects.all()
	return render(request,"show4.html",{'stocki':stocki})

def delete4(request,st_id):
	stoi= stock.objects.get(st_id=st_id)
	stoi.delete()
	return redirect("/show4")

hospital/templates/contracts.html
<DOCTYPE! HTML>
<HTML>
<head>
  <meta charset="UTF-8">
  <title>CONTRACTS</title>
     {% load staticfiles %}
    <h1>CONTRACTS</h1>
</head>
<style>
body {
  background-color: lightblue;
  background-image:url('https://nordiclifescience.org/wp-content/public_html/2020/02/iStock-1180780708-e1581456282469.jpg');
  background-size:cover;
  background-position:center;
  background-repeat:no-repeat;
  
}
#mov{
    font-style: italic;

}


h1 {
  color: red;
  text-align: center;
  opacity: 0.8;
  font-family:cursive;
}
H3{
  color:black;
}
#k {

  border: 10px solid black;
  outline-color: green;
  outline-width: 10p;
  margin: auto;
  padding: 20px;
}

p {

  font-family:courier;
  font-size: 20px;
  font-weight:bold;
}
#sub{
  width: 200px;  height: 100px;
  font-size: 40px;
  text-align: center;
  justify-content: center;
  align-items: center;
}
label{
  width: 240px;
  display: inline-block;
}
.submit:hover{

    background-color:rgb(85, 179, 85);
    border-radius:4px;
    font-family:cursive;
    box-shadow:0px 7px black;
    font-size:15px;
    cursor:pointer;
    color:white;
    padding: 2px 20px;
}



</style>
<body>
  <p id="mov">Please ensure the consistency and accuracy of the details </p>
  <form action="/con" method="POST" autocomplete="off">
    {% csrf_token %}
      <div id="k" class="ss-item-required">  
          <div class="con_div">
          <label for="Contract Company"><H3>Contract Company</H3></label>
          {{form.con_com}}
        </div>
        <div class="con_div1">
          <label for="amount"><H3>Amount</H3></label>
          {{form.con_amt}}
        </div>
        <div class="con_div2">
          <label for="Contract Equipment"><H3>Contract Equipment</H3></label>
          {{form.con_equip}}
        </div>
        <div style="text-align:center"><input type="submit" class="submit" value="Submit"></div><br>
         </div>
       </form>

  </body>
</HTML>

hospital/templates/departments.html
<DOCTYPE! HTML>
<HTML>
<head>
  <meta charset="UTF-8">
  <title>Departments</title>
  {% load staticfiles %}
  <h1>DEPARTMENTS</h1>
</head>
<style>
body {
  background-color: lightblue;
  background-image:url('https://nordiclifescience.org/wp-content/public_html/2020/02/iStock-1180780708-e1581456282469.jpg');
  background-size:cover;
  background-position:center;
  background-repeat:no-repeat;
  
}
#mov{
    font-style: italic;

}


h1 {
  color: red;
  text-align: center;
  opacity: 0.8;
  font-family:cursive;
}
H3{
  color:black;
}
#k {

  border: 10px solid black;
  outline-color: green;
  outline-width: 10p;
  margin: auto;
  padding: 20px;
}

p {

  font-family:courier;
  font-size: 20px;
  font-weight:bold;
}
#sub{
  width: 200px;  height: 100px;
  font-size: 40px;
  text-align: center;
  justify-content: center;
  align-items: center;
}
label{
  width: 240px;
  display: inline-block;
}
.submit{

    background-color:rgb(85, 179, 85);
    border-radius:4px;
    font-family:cursive;
    box-shadow:0px 7px black;
    font-size:15px;
    cursor:pointer;
    color:white;
    padding: 2px 20px;
}



</style>
<body>
  <p id="mov">Please ensure the consistency and accuracy of the details </p>
  <form  action="/dep" method="POST"  autocomplete="off">
            {% csrf_token %}
    <div id="K" class="ss-item-required"> 
          
        <label for="Department Name"><H3>Department Name</H3></label>
        <div class="typebox1">
          {{form.dept_name}}
          </div>
          <div style="text-align:center"><button type="submit" class="submit">Submit</button></div><br>
        </div><br><br><br>
      </form>

</body>
</HTML>

hospital/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Index</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static '/stylesheet.css' %}"/>
</head>
<style>
.back{
    
    height:680px;
    background-size:cover;
    background-position:center;
    background-repeat:no-repeat;
    background-image: url("https://img.freepik.com/free-vector/abstract-background-health-care-science-icon-pattern-medical-innovation-concept_44392-177.jpg?size=626&ext=jpg");
}
html,body, body * { 
    box-sizing: border-box; 
    font-family: 'Open Sans', sans-serif; 
    margin:0;
    padding:0;
    color:inherit;
    background-color:inherit;
 }
 body {
    background-image: url(pic1.jpg);
    background-size:  cover;
    background-position:center center;
    
  }

.login-register{
      height: 450px;
      width: 500px;
      margin-left: auto;
      margin-right: auto;
      margin-top:auto;
      padding:0 2em;
      margin-top:70px;
      border-radius: 5px;
      box-shadow: 0px 2px 7px rgba(0,0,0,0.2);
      overflow: hidden; 
      background: linear-gradient(180deg, rgba(65,4,119,1) 0%, rgba(22,147,198,1) 58%, rgba(255,255,255,0.1407913507199755) 82%);
      color:#ffffff;
  }

  /* Nav Buttons  */
  .nav-buttons {
    width: 100%;
    height: 100px;
    padding-top: 40px;
    opacity: 1;
    margin-bottom: 3em;
  }
  button {
      font-size: 1.5em;
      margin-right:1em;
      border:0px;
      cursor: pointer;
   
  }
  button:focus {
      outline: 0px;
  }
  button.active {
      padding-bottom: 10px;
      border-bottom: solid 2px #1059FF;
  } 
  /* footer: forgot section */
   #forgot {
        position: relative;
        height: 100px;
        margin-left: auto;
        margin-right: auto;
        text-align: center;
        padding-top: 24px;
        margin-top: -300px; 
        border-top: solid 1px rgba(255,255,255,.3);    
    }

    /* form styling */
    .form-group input {
        width: 100%;
        height: 35px;
        padding-left: 15px;
        border: none;
        border-radius: 5px;
        margin-bottom: 20px;
        background: rgba(255,255,255,.2);
    }
    .form-group label {
      text-transform: uppercase;
    }
    input.submit {
        font-weight: 700;
        text-transform: uppercase;
        font-size: 1em;
        text-align: center;
        color: rgba(255,255,255, 1);
        padding: 8px 0px;
        width: 100%;
        height: 35px;
        border: none;
        border-radius: 20px;
        margin-top: 23px;
        background-color: rgba(16,89,255, 1);
    
    }

    /* form positioning and animation */
    form, #forgot { 
        position: relative;
        transition: all .5s ease;
    }
    #loginBtn, #registerBtn {
        transition: all .5s ease;

    }
    form#loginform {
    left:0px;
    }
 
    form#registerform {
    left:500px;
    top:-230px;
    opacity: 0;;
   } 

</style>
<body class="back">
       
                <div class="login-register">
                    <div class="nav-buttons">
                        <h3>UPDATE VALUES</h3>
                        
                    </div>
                    <div class="form-group">
                            <form method="POST" class="post-form" autocomplete="off" action="/update/{{insti.inst_id}}">
                            	{% csrf_token %}
                            <div class="form1">
                            <label>Instrument Name</label>
                            <input type="text" name="inst_name" id="id_inst_name" required maxlength="100" value="{{insti.inst_name}}"/>
                        </div>
                        <div class="form2">
                            <label>Cost</label>
                             <input type="number" name="cost" id="id_cost" value="{{insti.cost}}"/>
                        </div>
                        	<input type="submit" value="UPDATE" class="submit"/>
                    </form>
                    </div>
                    </div>
</body>
</html>

hospital/templates/edit1.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Index1</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static '/stylesheet.css' %}"/>
</head>
<style>
.back{
    
    height:680px;
    background-size:cover;
    background-position:center;
    background-repeat:no-repeat;
    background-image: url("https://img.freepik.com/free-vector/abstract-background-health-care-science-icon-pattern-medical-innovation-concept_44392-177.jpg?size=626&ext=jpg");
}
html,body, body * { 
    box-sizing: border-box; 
    font-family: 'Open Sans', sans-serif; 
    margin:0;
    padding:0;
    color:inherit;
    background-color:inherit;
 }
 body {
    background-image: url(pic1.jpg);
    background-size:  cover;
    background-position:center center;
    
  }

.login-register{
      height: 400px;
      width: 500px;
      margin-left: auto;
      margin-right: auto;
      margin-top:auto;
      padding:0 2em;
      margin-top:70px;
      border-radius: 5px;
      box-shadow: 0px 2px 7px rgba(0,0,0,0.2);
      overflow: hidden; 
      background: linear-gradient(180deg, rgba(65,4,119,1) 0%, rgba(22,147,198,1) 58%, rgba(255,255,255,0.1407913507199755) 82%);
      color:#ffffff;
  }

  /* Nav Buttons  */
  .nav-buttons {
    width: 100%;
    height: 100px;
    padding-top: 40px;
    opacity: 1;
    margin-bottom: 3em;
  }
  button {
      font-size: 1.5em;
      margin-right:1em;
      border:0px;
      cursor: pointer;
   
  }
  button:focus {
      outline: 0px;
  }
  button.active {
      padding-bottom: 10px;
      border-bottom: solid 2px #1059FF;
  } 
  /* footer: forgot section */
   #forgot {
        position: relative;
        height: 100px;
        margin-left: auto;
        margin-right: auto;
        text-align: center;
        padding-top: 24px;
        margin-top: -300px; 
        border-top: solid 1px rgba(255,255,255,.3);    
    }

    /* form styling */
    .form-group input {
        width: 100%;
        height: 35px;
        padding-left: 15px;
        border: none;
        border-radius: 5px;
        margin-bottom: 20px;
        background: rgba(255,255,255,.2);
    }
    .form-group label {
      text-transform: uppercase;
    }
    input.submit {
        font-weight: 700;
        text-transform: uppercase;
        font-size: 1em;
        text-align: center;
        color: rgba(255,255,255, 1);
        padding: 8px 0px;
        width: 100%;
        height: 35px;
        border: none;
        border-radius: 20px;
        margin-top: 23px;
        background-color: rgba(16,89,255, 1);
    
    }

    /* form positioning and animation */
    form, #forgot { 
        position: relative;
        transition: all .5s ease;
    }
    #loginBtn, #registerBtn {
        transition: all .5s ease;

    }
    form#loginform {
    left:0px;
    }
 
    form#registerform {
    left:500px;
    top:-230px;
    opacity: 0;;
   } 
</style>

<body class="back">
	 <div class="login-register">
                    <div class="nav-buttons">
                        <h3>UPDATE VALUES</h3>
                        
                    </div>
                    <div class="form-group">
                            <form method="POST" class="post-form" autocomplete="off" action="/update1/{{depti.dept_id}}">
                            	{% csrf_token %}
                            <div class="form1">
                            <label>Department Name</label>
                            <input type="text" name="dept_name" id="id_dept_name" required maxlength="100" value="{{depti.dept_name}}"/>
                        </div>
                        <input type="submit" value="UPDATE" class="submit"/>
                       </form>
                    </div>
                    </div>
</body>
</html>

hospital/templates/instruments.html
<DOCTYPE! HTML>
<HTML>
<head>
  <meta charset="UTF-8">
  <title>Instruments</title>
  {% load staticfiles %}
  <h1>INSTRUMENTS</h1>
</head>
<style>
body {
  background-color: lightblue;
  background-image:url('https://nordiclifescience.org/wp-content/public_html/2020/02/iStock-1180780708-e1581456282469.jpg');
  background-size:cover;
  background-position:center;
  background-repeat:no-repeat;
  
}
#mov{
    font-style: italic;

}


h1 {
  color: red;
  text-align: center;
  opacity: 0.8;
  font-family:cursive;
}
H3{
  color:black;
}
#k {

  border: 10px solid black;
  outline-color: green;
  outline-width: 10p;
  margin: auto;
  padding: 20px;
}

p {

  font-family:courier;
  font-size: 20px;
  font-weight:bold;
}
#sub{
  width: 200px;  height: 100px;
  font-size: 40px;
  text-align: center;
  justify-content: center;
  align-items: center;
}
label{
  width: 240px;
  display: inline-block;
}
.submit{

    background-color:rgb(85, 179, 85);
    border-radius:4px;
    font-family:cursive;
    box-shadow:0px 7px black;
    font-size:15px;
    cursor:pointer;
    color:white;
    padding: 2px 20px;
    margin-top:px;
}
</style>

<body>
  <p id="mov">Please ensure the consistency and accuracy of the details </p>
  <form  action="/ins" method="POST"  autocomplete="off">
            {% csrf_token %}
    <div id="K" class="ss-item-required"> 
          
        <label for="Instrument Name"><H3>Instrument Name</H3></label>
        <div class="typebox1">
          {{form.inst_name}}
          </div>
          <label for="Cost"><H3>Cost</H3></label>
          <div class="typebox2">
          {{form.cost}}
          </div>
          <div style="text-align:center"><button type="submit" class="submit">Submit</button></div><br>
        </div><br><br><br>
      </form>
  <script src="script.js"></script>
</body>
</HTML>

hospital/templates/inventory_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Inventory Main</title>
</head>
<style>
.con1{
    background-color:white;
    height:200px;
    width:200px;
    margin-left:130px;
    margin-top:100px;
    border-radius:10px;
    box-shadow: 5px 2px black;
    float:left;
}
.type1{
    margin-left:28px;
    padding:20px;
    font-family:courier;
}
.type2{
        list-style:none;
        font-size:12px;
        margin-left:8px;
        margin-right:5px;
        text-align: justify;
        text-justify: inter-word;
        word-spacing:2px;
        font-family:cursive;
        
}
.back{
    
    height:750px;
    background-size:cover;
    background-position:center;
    background-repeat:no-repeat;
    background-image: url("https://www.wallpaperup.com/uploads/wallpapers/2016/02/26/899075/bf97d8ead40d4cba75ff0be7322e2516.jpg");

}
.click1{
    margin-left:35px;
    font-size:15px;
    background-color:rgb(85, 179, 85);
    border-radius:4px;
    box-shadow:0px 7px black;
    padding: 2px 20px;
    margin-top:25px;
    color:white;
    cursor:pointer;

}

.type3{
    margin-left:32px;
    padding:20px;
    font-family:courier;
}
.type4{
    list-style:none;
    font-size:12px;
    margin-left:8px;
    margin-right:5px;
    text-align: justify;
    text-justify: inter-word;
    word-spacing:2px;
    font-family:cursive;
    margin-top:5px;
}
.click2{

    margin-left:45px;
    font-size:15px;
    background-color:rgb(85, 179, 85);
    border-radius:4px;
    box-shadow:0px 7px black;
    padding: 8px 20px;
    margin-top:15px;
    color:white;
    cursor:pointer;

}
.type5{

    margin-left:30px;
    padding:20px;
    font-family:courier;
    margin-top:1px;
 }
.type6{
    list-style:none;
    font-size:12px;
    margin-left:8px;
    margin-right:5px;
    text-align: justify;
    text-justify: inter-word;
    word-spacing:2px;
    font-family:cursive;
    padding:5px;
    margin-:40px;

}
.click3{
    margin-left:50px;
    font-size:15px;
    background-color:rgb(85, 179, 85);
    border-radius:4px;
    box-shadow:0px 7px black;
    padding: 5px 20px;
    margin-top:25px;
    color:white;
    cursor:pointer;
    margin-top:15px;
}
.con2{
    background-color:white;
    height:200px;
    width:200px;
    margin-left:140px;
    margin-top:130px;
    border-radius:10px;
    box-shadow: 5px 2px black;
    float:left;
}
.type7{
    margin-left:45px;
    padding:20px;
    font-family:courier;
}
.button1{
            padding:250px;
}
</style>
<body class="back">
    <div class="container">
        <form method="POST" action="/show">
            {% csrf_token %}
        <div class="con2">
            <h4 class="type3">INSTRUMENTS</h4>
            <li class="type4">Data entry of all medical instruments</li>
            <input type="submit" value="ENTER" class="click2" name="sunmit">
        </div>
    </form>
       
       <form method="POST" action="/show1">
            {% csrf_token %}
        <div class="con2">
            <h4 class="type3">DEPARTMENTS</h4>
            <li class="type4">Data entry of all departments in a hospital</li>
            <input type="submit"value="ENTER" class="click2" name="sunmit">

        </div>
    </form>
       <form method="POST" action="/show2">
            {% csrf_token %}
        <div class="con2">
            <h4 class="type5">CONTARCTS</h4>
            <li class="type6">Data entry of contracts for equipments.</li>
            <input type="submit"value="ENTER" class="click3"name="sunmit">
      </div>
  </form>
        <form method="POST" action="/show3">
            {% csrf_token %}
        <div class="con2">
            <h4 class="type5">ORDERS</h4>
            <li class="type6">Data entry of orders for equipments.</li>
            <input type="submit"value="ENTER" class="click3" name="sunmit">
      </div>
  </form>
     <form method="POST" action="/show4">
            {% csrf_token %}
    <div class="con2">
            <h4 class="type7">STOCKS</h4>
            <li class="type4">Data entry of remaining equipments</li>
            <input type="submit"value="ENTER" class="click2" name="sunmit">

        </div>
    </form>
    

</body>
</html>

hospital/templates/orders.html
<DOCTYPE! HTML>
<HTML>
<head>
  <meta charset="UTF-8">
  <title>ORDERS</title>
     {% load staticfiles %}
    <h1>ORDERS</h1>
</head>
<style>
body {
  background-color: lightblue;
  background-image:url('https://nordiclifescience.org/wp-content/public_html/2020/02/iStock-1180780708-e1581456282469.jpg');
  background-size:cover;
  background-position:center;
  background-repeat:no-repeat;
  
}
#mov{
    font-style: italic;

}


h1 {
  color: red;
  text-align: center;
  opacity: 0.8;
  font-family:cursive;
}
H3{
  color:black;
}
#k {

  border: 10px solid black;
  outline-color: green;
  outline-width: 10p;
  margin: auto;
  padding: 20px;
}

p {

  font-family:courier;
  font-size: 20px;
  font-weight:bold;
}
#sub{
  width: 200px;  height: 100px;
  font-size: 40px;
  text-align: center;
  justify-content: center;
  align-items: center;
}
label{
  width: 240px;
  display: inline-block;
}
.submit{

    background-color:rgb(85, 179, 85);
    border-radius:4px;
    font-family:cursive;
    box-shadow:0px 7px black;
    font-size:15px;
    cursor:pointer;
    color:white;
    padding: 2px 20px;
}



</style>
<body>
  <p id="mov">Please ensure the consistency and accuracy of the details </p>
  <form action="/ord" method="POST" autocomplte="off">
          {% csrf_token %}
          <div id="k" class="ss-item-required"><H2 >ORDERS</H2>
          <div class="ord_div">
          <label for="I ID"><H3>Instrument ID</H3></label>
          {{form.Inst_id}}
        </div>
        <div class="ord_div1">
          <label for="C ID"><H3>Contract ID</H3></label>
          {{form.Con_id}}
        </div>
        <div class="ord_div2">
          <label for="DE ID"><H3>Department ID</H3></label>
          {{form.Dept_id}}
        </div>
        <div class="ord_div3">
          <label for="OR ID"><H3>Order Quantity</H3></label>
          {{form.ord_quan}}
        </div>
          <div style="text-align:center"><input type="submit" class="submit" value="Submit"></div><br>
        </div>
      </form>
    }
    </form>     
  </body>
</HTML>